import csv
import numpy as np
import matplotlib.pyplot as plt

results = []
with open("raw_files/2pixel_icm.csv") as csvfile: #this is the file containing the data of 200 frames generated by the SOFI tool
    reader = csv.reader(csvfile, quoting=csv.QUOTE_NONNUMERIC) # change contents to floats
    for row in reader: # each row is a list
        results.append(row)
        
results = np.asarray(results)
image = np.zeros([64,64,200])
for i in range(200):
    a = results[:,(i*64):(i*64)+64]
    image[:,:,i] = a

af_avg = image.mean(axis=2)

DF = []
for i in range(200):
    df = image[:,:,i] - af_avg
    DF.append(df)
DF = np.asarray(DF)

G2 = np.zeros([64,64])
for i in range(199):
    g = DF[i,:,:] * DF[i+1,:,:]
    G2 += g
G2 = G2/199
ICM = af_avg**2 - G2

plt.imshow(ICM,cmap='hot')
plt.axis("Off")
plt.show()
#plt.imsave("ICM.png",ICM,cmap='hot')
